---
voxelSize: "0.1"
#pathOut: "/media/gchahine/6063468A5237C350/transformerOutput/"
pathOut: "/home/gchahine/transformerOutput/"
autoMatchDir:
- "/run/user/1000/gvfs/sftp:host=boruvka.felk.cvut.cz,user=chahigeo/mnt/datagrid/personal/chahigeo/mapper/mapper_main/mapper_bridge/0"
- "/run/user/1000/gvfs/sftp:host=boruvka.felk.cvut.cz,user=chahigeo/mnt/datagrid/personal/chahigeo/mapper/mapper_main/mapper_bridge/1"
autoNameTemplate: "icp_local_"
transformsCsv: "/home/gchahine/packages/dream-multi-checker/build/2/19/ol_transforms11111.csv"
transformsMatcher: "/run/user/1000/gvfs/sftp:host=boruvka.felk.cvut.cz,user=chahigeo/mnt/datagrid/personal/chahigeo/matcher/matcher_main/matcher_bridge/transforms.csv"
transformsG2o: "/home/gchahine/packages/dream-optimizer/build/example_g2o_opt11111.g2o"
useG2o: "false"
useMatcher: "true"
transformPosesOnly: "false"
noOverlap: "false"
