---
voxelSize: "0.05"
pathOut: "/media/gchahine/6063468A5237C350/transformerOutput/"
autoMatchDir:
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/0/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/1/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/2/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/3/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/4/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/5/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/6/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/7/"
autoNameTemplate: "semantic_icp_"
transformsCsv: "/home/gchahine/packages/dream-multi-checker/build/ol_transforms.csv"
transformsG2o: "/home/gchahine/packages/dream-optimizer/build/example_g2o_opt.g2o"
useG2o: "true"
transformPosesOnly: "false"
noOverlap: "false"
