---
voxelSize: "0.05"
#pathOut: "/media/gchahine/6063468A5237C350/transformerOutput/"
pathOut: "/home/gchahine/transformerOutput/"
autoMatchDir:
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/0/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/1/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/2/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/3/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/4/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/5/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/6/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/7/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/8/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/9/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/10/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/11/"
autoNameTemplate: "semantic_icp_"
transformsCsv: "/home/gchahine/packages/dream-multi-checker/build/2/19/ol_transforms.csv"
transformsG2o: "/home/gchahine/packages/dream-optimizer/build/example_g2o_opt.g2o"
useG2o: "true"
transformPosesOnly: "true"
noOverlap: "false"
